[ADD] AboutFilm UI
sozidatel319/filmsrating pull request #3
Opened 2020-11-26 10:24 UTC by sozidatel319

2020-11-26 11:08 UTC, AndroidStudentClub requested changes

2020-11-26 11:08 UTC, AndroidStudentClub commented on app/src/main/res/layout/movie_details_fragment.xml
> +                android:background="@drawable/button_shape"
Лучше тоже стиль создать

2020-11-26 11:08 UTC, AndroidStudentClub commented on app/src/main/res/layout/movie_details_fragment.xml
> +                />
Не отформатировано

2020-11-26 11:08 UTC, AndroidStudentClub commented on app/src/main/res/layout/movie_details_fragment.xml
> +                />
Рекомендуется всё таки форматировать и вёрстку тоже - чтобы меньше было мердж конфликтов

2020-11-26 11:08 UTC, AndroidStudentClub commented on app/src/main/res/layout/item_actors.xml
> +            android:id="@+id/actorNameTextView"
В названия надо выбрать какой то один паттерн названия. Вот тут actorNameTextView - а ниже используются сокращения backBtn - это плохо. Я обычно предпочитаю называть полностью backButton. И там кстати не просто Button а ImageButton. Вобщем нужно в одном стиле именовать

2020-11-26 11:08 UTC, AndroidStudentClub commented on app/src/main/res/layout/movie_details_fragment.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
Не, LinearLayout в качестве корневого тут не подойдёт. Экраны в Android разные и соответсвтенно может быть ситуация когда контента много - и он не влезет в экран.

2020-11-26 11:08 UTC, AndroidStudentClub commented on app/src/main/res/layout/toolbar.xml
> +    android:layout_width="match_parent"
Вот это несколько не стандартное решение. Обычно такое делаю через обычный Toolbar и добавляют меню для отображения иконки

2020-11-26 11:08 UTC, AndroidStudentClub commented on app/src/main/res/values/styles.xml
> +        <item name="android:textSize">@dimen/dimens_16sp</item>
По-хорошему можно вынести в базовый стиль общие элементы типа @dimen/dimens_16sp @color/white и потом от них наследоваься. Все эти манипуляции служат для единственной цели - сокращение дублирования кода и как следствие уменьшение багов

2020-11-26 11:08 UTC, AndroidStudentClub commented on app/src/main/res/values/styles.xml
> +        <item name="android:textSize">@dimen/dimens_16sp</item>
Вот еще по стилям хорошая статья https://habr.com/ru/company/redmadrobot/blog/461201/

2020-11-26 11:09 UTC, AndroidStudentClub requested changes

2020-11-26 11:09 UTC, AndroidStudentClub commented on app/src/main/res/drawable/ic_back.xml
> +    android:width="18.025dp"
Можно использовать стандартный Toolbar - тогда это лишнее

2020-11-27 09:56 UTC, AndroidStudentClub commented on app/src/main/res/layout/toolbar.xml
> +    android:layout_width="match_parent"
Хотя, учитывая что там чекбокс - можно и так оставить. Toolbar android не очень удобно кастомизировать - тут проще реально свой сделать, чтобы потом легче с чекбоксом работать и его кастомизировать

2020-12-02 14:53 UTC, sozidatel319 commented on app/src/main/res/layout/movie_details_fragment.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
По этому поводу подскажите, что лучше использовать? ScrollView?

2020-12-02 14:54 UTC, closed without merging